### PR TITLE
Updated to 16.0.6

### PR DESCRIPTION
**Pull request by chilinux**
Added prep section to spec file to confirm tar.bz2 file integrity
Minor updates to README file

Signed-off-by: B Galliart <bgallia@gmail.com>

### CODE REVIEW

**Comment by gsanchietti** [comment]
Please fix the conflict.

**Comment by chilinux** [comment]
Please create a v16 branch

**Comment by gsanchietti** [comment]
Branch create, could you please check it again?

**Comment by chilinux** [comment]
Created new pull request against the new branch accordingly.  Closing this pull request.

**Pull request closed without merging**
